runtime: python39

entrypoint: gunicorn config.wsgi:application

env_variables:
  DJANGO_SETTINGS_MODULE: config.settings
  PYTHONUNBUFFERED: 'true'

handlers:
- url: /static
  static_dir: games/static/games

- url: /.*
  script: auto

env: flex

automatic_scaling:
  min_instances: 1
  max_instances: 3

# Optional: You can add health checks, readiness checks, etc. if needed
