# Generated by Django 4.2.16 on 2025-07-29 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon_class', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('cover_image_url', models.URLField(blank=True, default='https://via.placeholder.com/250x350.png?text=No+Image', max_length=500, null=True)),
                ('esrb', models.CharField(blank=True, max_length=10, null=True)),
                ('store_url', models.JSONField(blank=True, default=dict, null=True)),
                ('popularity_score', models.FloatField(default=0.0)),
                ('content_vector', models.JSONField(blank=True, null=True)),
                ('genres', models.ManyToManyField(blank=True, to='games.genre')),
                ('platforms', models.ManyToManyField(blank=True, to='games.platform')),
            ],
        ),
        migrations.CreateModel(
            name='GameSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_similarity', models.FloatField(default=0.0)),
                ('hybrid_similarity', models.FloatField(default=0.0)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('game1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_from', to='games.game')),
                ('game2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_to', to='games.game')),
            ],
            options={
                'unique_together': {('game1', 'game2')},
            },
        ),
    ]
