# Generated by Django 4.2.7 on 2025-07-14 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_store_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergameinteraction',
            name='game',
        ),
        migrations.RemoveField(
            model_name='usergameinteraction',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='usergamerating',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usergamerating',
            name='game',
        ),
        migrations.RemoveField(
            model_name='usergamerating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='user',
        ),
        migrations.DeleteModel(
            name='RecommendationCache',
        ),
        migrations.DeleteModel(
            name='UserGameInteraction',
        ),
        migrations.DeleteModel(
            name='UserGameRating',
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
