# Generated by Django 4.2.7 on 2025-07-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_userbookmark_usergamerating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usergamerating',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usergamerating',
            name='game',
        ),
        migrations.RemoveField(
            model_name='usergamerating',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserBookmark',
        ),
        migrations.DeleteModel(
            name='UserGameRating',
        ),
    ]
